name: Gitee repos mirror periodic job
on:
  # 如果需要 PR 触发把 push 前的#去掉
  # push:
  # 手动事件，如果需要手动触发把 workflow_dispatch 前的#去掉
  workflow_dispatch:
  # 计划事件
  schedule:
    - cron:  '45 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.10
      with:
        # 必选，需要同步的Github用户（源）
        src: github/tansjun
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/tang_sj
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}
