name: Sync with Gitee

on:
  schedule:
    - cron: '50 07 * * *' #另一个action每天21:45自动更新, 22:45自动同步(UTC时间)

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: actions/tang
      
      with:
        # 必选，需要同步的Github用户（源）
        src: github/tansjun
        # 必选，需要同步到的Gitee的用户（目的）
        dst: gitee/tang_sj
        # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
        dst_token:  ${{ secrets.GITEE_TOKEN }}

